version: "3.6"
services:
    app:
        depends_on:
         - db
        image: deliverysvc-image
        ports:
            - 6326:6326
        restart: always

    db:
        image: mysql
        restart: always
        volumes:
            - db-data:/var/lib/mysql
            
        environment:
            MYSQL_DATABASE: "statusdb"
            MYSQL_USER: "root"
            MYSQL_PASSWORD: "password"
            MYSQL_ROOT_PASSWORD: "plsdonthackme642"
volumes:
    db-data: